/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getString(memId: string): string
export function setString(memId: string, jsString: string): void
export function init(): void
export function clear(memId: string): void
export function getObject(memId: string): object
export function setObject(memId: string, jsObject: object): void
