/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getString(memId: string): string
export function setString(memId: string, callback: string): void
export function init(): void
export function clear(memId: string): void
